
development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: ping_pong_dev
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: ping_pong_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432
  template: template0