development:
  adapter: postgresql
  encoding: unicode
  database: pingpong_dev
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: pingpong_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432
